---
- name: Create temporary directory to store related files
  tempfile:
    state: directory
    suffix: gitlab
  register: gitlab_temp_dir

- name: Interpolate Ansible variables
  template:
    src: docker-compose.yml.j2
    dest: "{{ gitlab_temp_dir.path }}/docker-compose.yml"
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Deploy Gitlab in Swarm
  command: 'docker stack deploy --compose-file {{ gitlab_temp_dir.path }}/docker-compose.yml gitlab'
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

# - name: Record Traefik DNS
#   ara_record:
#     key: "gitlab_host"
#     value: "http://{{ gitlab_host }}"
#     type: url
#   tags:
#     - skip_ansible_lint